language: node_js
sudo: false

node_js:
- "8"
cache: npm

jobs:
  include:
    - stage: deploy branch
      script: npm run deploy
    - stage: alias to branch
      script: npm run alias
    - stage: deploy prod
      script: npm run deploy:prod
      if: branch = master AND type = push
    - stage: alias to prod
      script: npm run alias:prod
      if: branch = master AND type = push